### ISSUE TITLE
Change Initiative From Hud

### ISSUE THREAD

**Issue by Agnestorm** [reonZ/pf2e-hud#38]
Can't change skill used for initiative directly from the HUD have to do it in sheet itself.

**Comment by reonZ** [comment]
That is correct, you can't, just like you can't in the regular combat tracker.

**Comment by Agnestorm** [comment]
> That is correct, you can't, just like you can't in the regular combat tracker.

I just think it would be a nice addition, possibly a button on the HUD or something which opens the skill menu to roll initiative. The Token Action HUD has this, and I think your module is 10x better than that overall -- so I think having that kind of feature would be incredibly nice.

**Comment by reonZ** [comment]
I reopen this for now and will think about it, but no promises on if this will become a feature.

**Comment by Agnestorm** [comment]
Yeah. I just think it'd be a wonderful addition overall. Currently to roll initiative it's rather clunky with you having to open the sheet and then go to the drop-down menu and then choose the skill from there and roll initiative -- where compared to if that was something you could do on the HUD you wouldn't have to open your sheet nearly as much.

**Comment by reonZ** [comment]
You can technically roll your initiative from the HUD already in the `Extras` sidebar, it is more convenient than in the sheet because the dropdown to select a skill isn't permanent, while in the sheet, you need to change it back to `Perception` so you don't mis-roll the next initiative.

![Foundry_Virtual_Tabletop_CWpocHfiHN](https://github.com/user-attachments/assets/be55dc8a-6c82-4a80-8ec9-aee6f2233308)
